name: flashsale_project

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine # Bản này cực nhẹ và tích hợp sẵn giao diện Web
    container_name: flashsale_rabbitmq
    ports:
      - "5672:5672"   # Port để Spring Boot gửi/nhận tin nhắn
      - "15672:15672" # Port để bạn mở trình duyệt xem giao diện Web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin