server:
  port: 8080


spring:
  application:
    name: flash-sale-campaign

  datasource:
    url: jdbc:postgresql://localhost:5432/flashsale_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh_expiration: 604800000

